package gextto

import "strings"

// uiweb_tooltips.go ports rextto's `setting_tooltip` descriptions so the
// settings rows (and the integration/config sections) show a helpful tooltip
// instead of a bare key.

// uiSettingTooltipText maps a setting key to a short description.
var uiSettingTooltipText = map[string]string{
	"libtorrent_enabled":                           "Attiva o disattiva del tutto il client libtorrent integrato.",
	"libtorrent_dynamic_queue":                     "Regola automaticamente quanti torrent sono attivi in base al carico.",
	"libtorrent_dynamic_queue_min":                 "Numero minimo di download dinamici. La coda cambia al massimo di uno per volta.",
	"libtorrent_dynamic_queue_max":                 "Numero massimo di download dinamici. Servono campioni consecutivi coerenti prima di aumentare la coda.",
	"libtorrent_dont_count_slow_torrents":          "I torrent che non trasferiscono dati non consumano uno slot attivo.",
	"libtorrent_stall_after_min":                   "Dopo questi minuti senza avanzamento il torrent viene considerato stalled.",
	"libtorrent_stall_retry_min":                   "Intervallo tra i tentativi di reannounce dei torrent stalled.",
	"libtorrent_stall_giveup_min":                  "Dopo questo periodo senza progresso il torrent viene rimosso; 0 disabilita la rimozione automatica.",
	"libtorrent_auto_optimize":                     "Applica periodicamente l'ottimizzazione di cache, buffer e coda in base alle risorse.",
	"libtorrent_sequential":                        "Scarica i file in ordine sequenziale invece che a pezzi sparsi.",
	"libtorrent_extra_settings":                    "Impostazioni libtorrent avanzate, una per riga nel formato chiave=valore.",
	"libtorrent_active_downloads":                  "Valore base dei download attivi; con la coda dinamica viene adattato a runtime.",
	"libtorrent_active_seeds":                      "Valore base dei seed attivi; con la coda dinamica scende a 1 quando ci sono download in coda.",
	"libtorrent_active_limit":                      "Valore base del limite di torrent attivi; con la coda dinamica diventa max(base, download + seed + 2).",
	"libtorrent_seed_ratio":                        "Rapporto upload/download dopo cui fermare il seeding (0 = infinito).",
	"libtorrent_seed_time":                         "Limite di seeding in minuti, usato solo se Seed massimo (giorni) è 0.",
	"libtorrent_seed_time_days":                    "Limite principale di seeding in giorni; se maggiore di 0 prevale sul limite in minuti.",
	"auto_remove_completed":                        "Elimina dalla sessione i torrent completati appena raggiungono i limiti di seed.",
	"libtorrent_connections_limit":                 "Numero massimo di connessioni peer simultanee a livello di sessione.",
	"libtorrent_upload_slots_limit":                "Numero di peer non bloccati in upload (-1 = automatico).",
	"libtorrent_half_open_limit":                   "Numero massimo di connessioni in fase di apertura (-1 = automatico).",
	"libtorrent_max_connections_per_torrent":       "Limite di connessioni per singolo torrent (-1 = illimitato).",
	"libtorrent_max_uploads_per_torrent":           "Limite di upload per singolo torrent (-1 = illimitato).",
	"libtorrent_aio_threads":                       "Thread dedicati alle operazioni su disco (-1 = automatico).",
	"libtorrent_cache_size":                        "Dimensione della cache disco in blocchi (-1 = automatico).",
	"libtorrent_cache_expiry":                      "Secondi di inattività dopo cui un blocco esce dalla cache.",
	"libtorrent_alert_queue_size":                  "Dimensione della coda degli alert di libtorrent.",
	"libtorrent_dht":                               "Abilita la rete DHT per trovare peer senza tracker.",
	"libtorrent_pex":                               "Peer Exchange: scambio peer con altri client.",
	"libtorrent_lsd":                               "Local Service Discovery: trova peer nella rete locale.",
	"libtorrent_upnp":                              "Apre le porte del router automaticamente con UPnP.",
	"libtorrent_natpmp":                            "Apre le porte del router automaticamente con NAT-PMP.",
	"libtorrent_utp":                               "Abilita il protocollo uTP (UDP) oltre a TCP.",
	"libtorrent_prefer_rc4":                        "Preferisce la cifratura RC4 sulle connessioni.",
	"libtorrent_announce_to_all_trackers":          "Annuncia a tutti i tracker, non solo al primo di ogni tier.",
	"libtorrent_announce_to_all_tiers":             "Annuncia a tutti i tier, non solo al primo.",
	"libtorrent_allow_multiple_connections_per_ip": "Permette più connessioni dallo stesso indirizzo IP.",
	"libtorrent_announce_interval":                 "Intervallo minimo (secondi) tra due announce allo stesso tracker.",
	"libtorrent_torrent_connect_boost":             "Numero di tentativi di connessione extra all'avvio del torrent.",
	"libtorrent_dht_bootstrap_nodes":               "Nodi DHT iniziali (host:porta separati da virgola).",
	"libtorrent_encryption":                        "Politica di cifratura: 0 disabilitata, 1 abilitata, 2 forzata.",
	"libtorrent_apply_ip_filter":                   "Applica il filtro IP anche ai tracker.",
	"libtorrent_ipfilter_url":                      "File locale o URL della lista IP da bloccare.",
	"libtorrent_proxy_host":                        "Host del proxy per il traffico torrent.",
	"libtorrent_proxy_port":                        "Porta del proxy (0 = nessun proxy).",
	"libtorrent_listen_interfaces":                 "Interfacce e porte di ascolto (es. 0.0.0.0:6881-6891).",
	"libtorrent_outgoing_interface":                "Killswitch VPN: interfaccia usata per tutto il traffico BitTorrent in uscita.",
	"libtorrent_dl_limit":                          "Limite globale di download in KiB/s (0 = illimitato).",
	"libtorrent_ul_limit":                          "Limite globale di upload in KiB/s (0 = illimitato).",
	"libtorrent_sched_enabled":                     "Attiva la fascia oraria con limiti di velocità diversi.",
	"libtorrent_sched_start":                       "Ora di inizio della programmazione (HH:MM).",
	"libtorrent_sched_end":                         "Ora di fine della programmazione (HH:MM).",
	"libtorrent_sched_days":                        "Giorni attivi: 0=Lun … 6=Dom (es. 0,1,2,3,4).",
	"libtorrent_sched_dl_limit":                    "Limite di download in KiB/s durante la programmazione.",
	"libtorrent_sched_ul_limit":                    "Limite di upload in KiB/s durante la programmazione.",
	"flaresolverr_url":                             "URL del servizio FlareSolverr per aggirare Cloudflare.",
	"refresh_interval":                             "Intervallo tra le ricerche automatiche di serie e film, in secondi (21600 = 6 ore).",
	"max_release_age_days":                         "Ignora le release più vecchie di N giorni (0 = nessun limite).",
	"gap_filling":                                  "Attiva il riempimento dei buchi (episodi mancanti) dalle release disponibili.",
	"gap_fill_max_per_series":                      "Numero massimo di gap da cercare per serie in un ciclo (0 = illimitato).",
	"gap_deep_interval_hours":                      "Ogni quante ore fare una ricerca live mirata sugli indexer per i gap.",
	"gap_deep_max_per_cycle":                       "Numero massimo di ricerche live per ciclo.",
	"delay_torrent_minutes":                        "Ritarda l'avvio dei download delle serie di questo numero di minuti. 0 avvia subito.",
	"delay_movies_minutes":                         "Ritarda l'avvio dei download dei film di questo numero di minuti. 0 avvia subito.",
	"delay_bypass_score":                           "Se una release raggiunge almeno questo punteggio, ignora il delay configurato.",
	"housekeeping_enabled":                         "Attiva la pulizia periodica dei dati tecnici e dello storico.",
	"housekeeping_interval_hours":                  "Intervallo tra due housekeeping automatici, in ore.",
	"housekeeping_retain_cycles":                   "Numero di statistiche dei cicli di ricerca da conservare.",
	"housekeeping_seen_days":                       "Elimina le righe storiche delle release viste nei feed più vecchie di N giorni.",
	"housekeeping_history_days":                    "Elimina dallo Storico download le righe dei torrent rimossi più vecchie di N giorni.",
	"media_info_backfill_enabled":                  "Analizza periodicamente con ffprobe i file già presenti che non hanno ancora MediaInfo.",
	"media_info_backfill_interval_minutes":         "Minuti tra due passaggi del backfill MediaInfo.",
	"media_info_backfill_batch":                    "Numero massimo di file analizzati in ogni passaggio MediaInfo.",
	"notify_telegram":                              "Invia le notifiche su Telegram.",
	"telegram_bot_token":                           "Token del bot Telegram (da @BotFather).",
	"telegram_chat_id":                             "ID della chat/canale dove inviare le notifiche.",
	"notify_email":                                 "Invia le notifiche via email.",
	"email_smtp":                                   "Server SMTP nel formato host:porta (es. smtp.gmail.com:587).",
	"email_from":                                   "Indirizzo mittente delle email di notifica.",
	"email_to":                                     "Destinatari delle email (separati da virgola).",
	"email_password":                               "Password/app-password SMTP (non visualizzata).",
	"notify_webhook_url":                           "URL del webhook a cui inviare gli eventi.",
	"notify_webhook_secret":                        "Segreto HMAC per firmare le richieste al webhook.",
	"rename_episodes":                              "Rinomina i file scaricati usando i metadati TMDB.",
	"cleanup_upgrades":                             "Sostituisce versioni inferiori già archiviate con upgrade migliori.",
	"cleanup_action":                               "Cosa fare con i file sostituiti: sposta nel trash o elimina.",
	"tmdb_language":                                "Lingua usata per i metadati TMDB (es. it-IT, en-US).",
	"default_language":                             "Lingua preferita di default per serie e film (es. ita, eng).",
	"blacklist":                                    "Parole vietate, una per riga: le release che le contengono vengono scartate.",
	"archive_root":                                 "Cartella di archivio predefinita per i contenuti senza percorso dedicato.",
	"trash_path":                                   "Cartella dove vengono spostati i file sostituiti/duplicati.",
	"libtorrent_dir":                               "Cartella di download predefinita di libtorrent.",
	"libtorrent_temp_dir":                          "Cartella temporanea per i download in corso.",
	"libtorrent_ramdisk_dir":                       "RAM disk da usare per i download in corso, se disponibile.",
	"libtorrent_ramdisk_enabled":                   "Scarica in RAM i torrent che rientrano nella soglia; i più grandi vanno su disco.",
	"libtorrent_ramdisk_threshold_gb":              "Dimensione massima di un singolo torrent ammesso sul RAM disk (GB).",
	"libtorrent_ramdisk_margin_gb":                 "Spazio libero da lasciare sul RAM disk una volta completato il download (GB).",
	"libtorrent_ramdisk_min_free_bytes":            "Spazio minimo libero in byte richiesto per usare il RAM disk. 0 = usa il margine configurato.",
	"libtorrent_port_min":                          "Porta minima della sessione libtorrent (richiede il riavvio del servizio).",
	"libtorrent_port_max":                          "Porta massima della sessione libtorrent (richiede il riavvio del servizio).",
	"min_free_space_gb":                            "Spazio libero minimo (GB) sulla cartella download: sotto questa soglia il ciclo non avvia download.",
	"trash_retention_days":                         "La pulizia del trash elimina solo i file più vecchi di N giorni (0 = elimina tutto).",
	"archive_retention_days":                       "Elimina dall'archivio le release più vecchie di N giorni (0 = conserva sempre).",
	"archive_cleanup_enabled":                      "Abilita la pulizia automatica dell'archivio secondo età massima e numero minimo da conservare.",
	"archive_max_age_days":                         "Età massima delle release in archivio, in giorni (0 = nessun limite).",
	"archive_keep_min":                             "Numero minimo di release recenti da conservare sempre in archivio.",
	"cleanup_min_score_diff":                       "Differenza minima di punteggio per sostituire un file esistente con uno migliore (cleanup).",
	"upgrade_min_score_diff":                       "Differenza minima di punteggio per sostituire un file con un upgrade migliore.",
	"tvdb_api_key":                                 "Chiave API v4 di TheTVDB per ricerca serie e metadati.",
	"tvdb_language":                                "Lingua preferita per i metadati TVDB (es. ita, eng).",
	"stop_on_old_page_threshold":                   "Quante pagine di elenco leggere per ogni feed (3 è un buon compromesso).",
	"rename_verify_interval":                       "Ogni quante ore verificare che i file archiviati/rinominati siano ancora presenti.",
	"move_episodes":                                "Sposta gli episodi e i season pack nella cartella archivio invece di copiarli.",
	"debug_enabled":                                "Attiva log dettagliati e diagnostiche periodiche per il debug.",
	"jellyfin_url":                                 "URL del server Jellyfin (es. http://127.0.0.1:8096).",
	"jellyfin_api_key":                             "API key generata in Jellyfin → Dashboard → API Keys.",
	"plex_url":                                     "URL del server Plex (es. http://127.0.0.1:32400).",
	"plex_token":                                   "Token X-Plex-Token per accedere alla libreria Plex.",
	"trakt_client_id":                              "Client ID dell'app creata su trakt.tv.",
	"trakt_client_secret":                          "Client secret dell'app creata su trakt.tv.",
	"trakt_calendar_days":                          "Quanti giorni avanti mostrare nel calendario Trakt.",
	"simkl_client_id":                              "Client ID dell'app Simkl.",
	"simkl_calendar_days":                          "Quanti giorni avanti mostrare nel calendario Simkl.",
	"active":                                       "Attiva o disattiva il daemon Gextto: cicli automatici e download.",
	"websearch_engines":                            "Motori di ricerca web usati per il gap-filling quando feed e indexer non trovano nulla.",
	"content_filters":                              "Le release che contengono queste parole o script (es. [porno]) vengono escluse.",
	"libtorrent_preallocate":                       "Riserva subito tutto lo spazio su disco prima di iniziare il download.",
	"tmdb_api_key":                                 "Chiave API TMDB per titoli, poster e metadati.",
	"libtorrent_torrent_copy_dir":                  "Copia qui i file .torrent dei download (vuoto = nessuna copia).",
	"torrent_backend":                              "Motore torrent attivo (libtorrent, qBittorrent o anacrolix).",
	"qbittorrent_url":                              "URL dell'interfaccia Web di qBittorrent (es. http://127.0.0.1:8080).",
	"qbittorrent_username":                         "Utente dell'interfaccia Web di qBittorrent.",
	"qbittorrent_password":                         "Password dell'interfaccia Web di qBittorrent (non visualizzata).",
	"qbittorrent_category":                         "Categoria applicata ai torrent aggiunti a qBittorrent.",
	"qbittorrent_tag":                              "Tag applicato ai torrent aggiunti a qBittorrent.",
	"qbittorrent_request_timeout_secs":             "Timeout in secondi delle richieste HTTP verso qBittorrent.",
	"qbittorrent_poll_interval_ms":                 "Intervallo in millisecondi tra due letture dello stato dei torrent.",
	"qbittorrent_path_mappings":                    "Mappatura dei percorsi tra Gextto e qBittorrent, una per riga (locale=remoto).",
	"qbittorrent_managed":                          "Gextto scarica da sé l'ultima release di qBittorrent, la installa nella cartella dell'applicazione (accanto a gexttod), la avvia e la ferma con il servizio e la aggiorna (con backup e rollback). Il motore in uso però si sceglie dalla voce «Motore torrent»: questa opzione non lo cambia.",
	"anacrolix_path_mappings":                      "Mappatura dei percorsi tra Gextto e il motore anacrolix (locale=remoto).",
	"anacrolix_data_dir":                           "Cartella dati del motore anacrolix (stato e resume).",
	"anacrolix_listen_port":                        "Porta di ascolto del motore anacrolix.",
	"anacrolix_tcp":                                "Abilita il trasporto TCP.",
	"anacrolix_utp":                                "Abilita il trasporto uTP (UDP).",
	"anacrolix_dht":                                "Abilita la rete DHT.",
	"anacrolix_pex":                                "Abilita il Peer Exchange.",
	"anacrolix_trackers":                           "Tracker aggiuntivi applicati ai nuovi torrent, separati da virgola.",
	"anacrolix_upnp":                               "Apre le porte con UPnP/NAT-PMP.",
	"anacrolix_dht_bootstrap_nodes":                "Nodi bootstrap DHT (host:porta separati da virgola).",
	"anacrolix_max_conns_per_torrent":              "Numero massimo di connessioni per torrent (-1 = illimitato).",
	"anacrolix_download_limit_kib":                 "Limite globale di download in KiB/s (0 = illimitato).",
	"anacrolix_upload_limit_kib":                   "Limite globale di upload in KiB/s (0 = illimitato).",
	"anacrolix_piece_hashers":                      "Numero di hasher dei pezzi per torrent (-1 = automatico).",
	"anacrolix_max_unverified_mb":                  "Byte massimi non verificati in MB per torrent.",
	"anacrolix_ipfilter_path":                      "File locale della lista IP da bloccare.",
	"anacrolix_apply_ip_filter":                    "Applica il filtro IP anche ai tracker.",
	"anacrolix_proxy_type":                         "Tipo di proxy per il traffico torrent.",
	"anacrolix_proxy_host":                         "Host del proxy.",
	"anacrolix_proxy_port":                         "Porta del proxy.",
	"anacrolix_proxy_user":                         "Utente del proxy, se richiesto.",
	"anacrolix_proxy_password":                     "Password del proxy, se richiesta (non visualizzata).",
}

// uiSettingTooltip returns the tooltip for a setting key. Score weights without
// a specific entry get a generic explanation.
func uiSettingTooltip(key string) string {
	if text, ok := uiSettingTooltipText[key]; ok {
		return text
	}
	if strings.HasPrefix(key, "score_") {
		return "Peso usato per scegliere la release migliore: più alto = più preferito."
	}
	return ""
}
