package gextto

import "strings"

// uiweb_tooltips.go ports rextto's `setting_tooltip` descriptions so the
// settings rows (and the integration/config sections) show a helpful tooltip
// instead of a bare key.

// uiSettingTooltipText maps a setting key to a short description.
var uiSettingTooltipText = map[string]string{
	"libtorrent_enabled":                           "Attiva o disattiva del tutto il client libtorrent integrato.",
	"libtorrent_dynamic_queue":                     "Regola automaticamente quanti torrent sono attivi in base al carico.",
	"libtorrent_dynamic_queue_min":                 "Numero minimo di download dinamici. La coda cambia al massimo di uno per volta.",
	"libtorrent_dynamic_queue_max":                 "Numero massimo di download dinamici. Servono campioni consecutivi coerenti prima di aumentare la coda.",
	"libtorrent_dont_count_slow_torrents":          "I torrent che non trasferiscono dati non consumano uno slot attivo.",
	"libtorrent_stall_after_min":                   "Dopo questi minuti senza avanzamento il torrent viene considerato stalled.",
	"libtorrent_stall_retry_min":                   "Intervallo tra i tentativi di reannounce dei torrent stalled.",
	"libtorrent_stall_giveup_min":                  "Dopo questo periodo senza progresso il torrent viene rimosso automaticamente. Imposta 0 per disattivare completamente la rimozione automatica per stallo.",
	"libtorrent_dead_swarm_giveup_min":             "Stallo con zero seeder (dead swarm): rimosso dopo questo periodo, più breve, e la puntata viene ricercata di nuovo subito. Imposta 0 per usare la soglia generale.",
	"libtorrent_auto_optimize":                     "Applica periodicamente l'ottimizzazione di cache, buffer e coda in base alle risorse.",
	"libtorrent_sequential":                        "Scarica i file in ordine sequenziale invece che a pezzi sparsi.",
	"libtorrent_extra_settings":                    "Impostazioni libtorrent avanzate, una per riga nel formato chiave=valore.",
	"libtorrent_active_downloads":                  "Valore base dei download attivi; con la coda dinamica viene adattato a runtime.",
	"libtorrent_active_seeds":                      "Valore base dei seed attivi; con la coda dinamica scende a 1 quando ci sono download in coda.",
	"libtorrent_active_limit":                      "Valore base del limite di torrent attivi; con la coda dinamica diventa max(base, download + seed + 2).",
	"libtorrent_seed_ratio":                        "Rapporto upload/download dopo cui fermare il seeding (0 = infinito).",
	"libtorrent_seed_time":                         "Limite di seeding in minuti, usato solo se Seed massimo (giorni) è 0.",
	"libtorrent_seed_time_days":                    "Limite principale di seeding in giorni; se maggiore di 0 prevale sul limite in minuti.",
	"auto_remove_completed":                        "Attivo: a fine seed il torrent completato viene tolto dalla sessione (come «Pulisci completati»). Spento: a fine seed il torrent resta nell'elenco come Completato e lo rimuovi tu con «Pulisci completati». Non influisce su dove vengono spostati i file.",
	"libtorrent_connections_limit":                 "Numero massimo di connessioni peer simultanee a livello di sessione.",
	"libtorrent_upload_slots_limit":                "Numero di peer non bloccati in upload (-1 = automatico).",
	"libtorrent_half_open_limit":                   "Numero massimo di connessioni in fase di apertura (-1 = automatico).",
	"libtorrent_max_connections_per_torrent":       "Limite di connessioni per singolo torrent (-1 = illimitato).",
	"libtorrent_max_uploads_per_torrent":           "Limite di upload per singolo torrent (-1 = illimitato).",
	"libtorrent_aio_threads":                       "Thread dedicati alle operazioni su disco (-1 = automatico).",
	"libtorrent_cache_size":                        "Dimensione della cache disco in blocchi (-1 = automatico).",
	"libtorrent_cache_expiry":                      "Secondi di inattività dopo cui un blocco esce dalla cache.",
	"libtorrent_alert_queue_size":                  "Dimensione della coda degli alert di libtorrent.",
	"libtorrent_dht":                               "Abilita la rete DHT per trovare peer senza tracker.",
	"libtorrent_pex":                               "Peer Exchange: scambio peer con altri client.",
	"libtorrent_lsd":                               "Local Service Discovery: trova peer nella rete locale.",
	"libtorrent_upnp":                              "Apre le porte del router automaticamente con UPnP.",
	"libtorrent_natpmp":                            "Apre le porte del router automaticamente con NAT-PMP.",
	"libtorrent_utp":                               "Abilita il protocollo uTP (UDP) oltre a TCP.",
	"libtorrent_prefer_rc4":                        "Preferisce la cifratura RC4 sulle connessioni.",
	"libtorrent_announce_to_all_trackers":          "Annuncia a tutti i tracker, non solo al primo di ogni tier.",
	"libtorrent_announce_to_all_tiers":             "Annuncia a tutti i tier, non solo al primo.",
	"libtorrent_allow_multiple_connections_per_ip": "Permette più connessioni dallo stesso indirizzo IP.",
	"libtorrent_announce_interval":                 "Intervallo minimo (secondi) tra due announce allo stesso tracker.",
	"libtorrent_torrent_connect_boost":             "Numero di tentativi di connessione extra all'avvio del torrent.",
	"libtorrent_dht_bootstrap_nodes":               "Nodi DHT iniziali (host:porta separati da virgola).",
	"libtorrent_encryption":                        "Politica di cifratura: 0 disabilitata, 1 abilitata, 2 forzata.",
	"libtorrent_apply_ip_filter":                   "Applica il filtro IP anche ai tracker.",
	"libtorrent_ipfilter_url":                      "File locale o URL della lista IP da bloccare.",
	"libtorrent_listen_interfaces":                 "Indica dove libtorrent accetta connessioni: 0.0.0.0:6881-6891 per tutte le interfacce, 127.0.0.1:6881 solo in locale, oppure wg0:6881/tun0:6881 per una VPN. Il valore proposto va bene nella maggior parte dei casi.",
	"libtorrent_outgoing_interface":                "Killswitch VPN: interfaccia usata per tutto il traffico BitTorrent in uscita.",
	"libtorrent_dl_limit":                          "Limite globale di download in KiB/s (0 = illimitato).",
	"libtorrent_ul_limit":                          "Limite globale di upload in KiB/s (0 = illimitato).",
	"libtorrent_sched_enabled":                     "Attiva la fascia oraria con limiti di velocità diversi.",
	"libtorrent_sched_start":                       "Ora di inizio della programmazione (HH:MM).",
	"libtorrent_sched_end":                         "Ora di fine della programmazione (HH:MM).",
	"libtorrent_sched_days":                        "Giorni attivi: 0=Lun … 6=Dom (es. 0,1,2,3,4).",
	"libtorrent_sched_dl_limit":                    "Limite di download in KiB/s durante la programmazione.",
	"libtorrent_sched_ul_limit":                    "Limite di upload in KiB/s durante la programmazione.",
	"flaresolverr_url":                             "URL del servizio FlareSolverr per aggirare Cloudflare.",
	"refresh_interval":                             "Intervallo tra le ricerche automatiche di serie e film, in secondi (21600 = 6 ore).",
	"max_release_age_days":                         "Ignora le release più vecchie di N giorni (0 = nessun limite). Le release senza data sono considerate pubblicate oggi.",
	"gap_filling":                                  "Attiva il riempimento dei buchi (episodi mancanti) dalle release disponibili.",
	"gap_fill_max_per_series":                      "Numero massimo di gap da cercare per serie in un ciclo (0 = illimitato).",
	"gap_deep_interval_hours":                      "Ogni quante ore fare una ricerca live mirata sugli indexer per i gap.",
	"gap_deep_max_per_cycle":                       "Numero massimo di ricerche live per ciclo.",
	"cycle_title_search":                           "Cerca i titoli su indexer durante il ciclo: auto (solo se non ci sono feed configurati), yes (sempre), no (mai, usa solo feed e archivio locale).",
	"delay_torrent_minutes":                        "Ritarda l'avvio dei download delle serie di questo numero di minuti. 0 avvia subito.",
	"delay_movies_minutes":                         "Ritarda l'avvio dei download dei film di questo numero di minuti. 0 avvia subito.",
	"delay_bypass_score":                           "Se una release raggiunge almeno questo punteggio, ignora il delay configurato.",
	"housekeeping_enabled":                         "Attiva la pulizia periodica dei dati tecnici e dello storico.",
	"housekeeping_interval_hours":                  "Intervallo tra due housekeeping automatici, in ore.",
	"temp_orphan_cleanup_enabled":                  "Ogni 30 minuti sposta nel cestino file e cartelle della cartella temporanea dei download che non appartengono a nessun torrent in lista e non sono cambiati da almeno il numero di giorni indicato. Non cancella nulla: restano nel cestino finché non lo svuoti.",
	"temp_orphan_min_age_days":                     "Da quanti giorni un elemento della cartella temporanea deve essere fermo, senza torrent in lista, per essere spostato nel cestino.",
	"housekeeping_retain_cycles":                   "Numero di statistiche dei cicli di ricerca da conservare.",
	"housekeeping_seen_days":                       "Elimina le righe storiche delle release viste nei feed più vecchie di N giorni.",
	"housekeeping_history_days":                    "Elimina dallo Storico download le righe dei torrent rimossi più vecchie di N giorni.",
	"housekeeping_error_age_days":                  "Elimina le schede dei torrent in errore più vecchie di N giorni (minimo 1).",
	"housekeeping_gap_log_days":                    "Elimina il log delle ricerche degli episodi mancanti più vecchio di N giorni.",
	"housekeeping_upgrade_backup_days":             "Elimina i backup dei file sostituiti dagli upgrade più vecchi di N giorni.",
	"media_info_backfill_enabled":                  "Analizza periodicamente con ffprobe i file già presenti che non hanno ancora MediaInfo.",
	"media_info_backfill_interval_minutes":         "Minuti tra due passaggi del backfill MediaInfo.",
	"media_info_backfill_batch":                    "Numero massimo di file analizzati in ogni passaggio MediaInfo.",
	"notify_telegram":                              "Invia le notifiche su Telegram.",
	"telegram_bot_token":                           "Token del bot Telegram (da @BotFather).",
	"telegram_chat_id":                             "ID della chat/canale dove inviare le notifiche.",
	"notify_email":                                 "Invia le notifiche via email.",
	"email_smtp":                                   "Server SMTP nel formato host:porta (es. smtp.gmail.com:587).",
	"email_from":                                   "Indirizzo mittente delle email di notifica.",
	"email_to":                                     "Destinatari delle email (separati da virgola).",
	"email_password":                               "Password/app-password SMTP (non visualizzata).",
	"notify_webhook_url":                           "URL del webhook a cui inviare gli eventi.",
	"notify_webhook_secret":                        "Segreto HMAC per firmare le richieste al webhook.",
	"rename_episodes":                              "Rinomina i file scaricati usando i metadati TMDB.",
	"cleanup_upgrades":                             "Sostituisce versioni inferiori già archiviate con upgrade migliori.",
	"movies_flat_files":                            "Se Sì, un film arrivato dentro una cartella torrent viene spostato nella cartella film come file singolo, portando con sé sottotitoli e artwork. Se No, resta nella sua cartella.",
	"cleanup_action":                               "Cosa fare con i file sostituiti: sposta nel trash o elimina.",
	"tmdb_language":                                "Lingua usata per i metadati TMDB (es. it-IT, en-US).",
	"default_language":                             "Lingua preferita di default per serie e film (es. ita, eng).",
	"blacklist":                                    "Parole vietate, una per riga: le release che le contengono vengono scartate.",
	"archive_root":                                 "Cartella di archivio predefinita per i contenuti senza percorso dedicato.",
	"trash_path":                                   "Cartella dove vengono spostati i file sostituiti/duplicati (se lasciata vuota usa la sottocartella trash nella cartella dati).",
	"libtorrent_dir":                               "Cartella di download predefinita per tutti i motori.",
	"libtorrent_temp_dir":                          "Cartella temporanea per i download in corso.",
	"libtorrent_ramdisk_dir":                       "RAM disk da usare per i download in corso, se disponibile.",
	"libtorrent_ramdisk_enabled":                   "Scarica in RAM i torrent che rientrano nella soglia; i più grandi vanno su disco.",
	"libtorrent_ramdisk_threshold_gb":              "Dimensione massima di un singolo torrent ammesso sul RAM disk (GB).",
	"libtorrent_ramdisk_margin_gb":                 "Spazio libero da lasciare sul RAM disk una volta completato il download (GB).",
	"libtorrent_ramdisk_min_free_bytes":            "Spazio minimo libero in byte richiesto per usare il RAM disk. 0 = usa il margine configurato.",
	"libtorrent_port_min":                          "Porta minima della sessione libtorrent (richiede il riavvio del servizio).",
	"libtorrent_port_max":                          "Porta massima della sessione libtorrent (richiede il riavvio del servizio).",
	"min_free_space_gb":                            "Spazio libero minimo (GB) sulla cartella download: sotto questa soglia il ciclo non avvia download.",
	"trash_retention_days":                         "Giorni di conservazione per le pulizie non forzate; 0 elimina tutto il contenuto del cestino. Le azioni manuali della UI svuotano sempre subito il cestino.",
	"archive_cleanup_enabled":                      "Abilita la pulizia automatica dell'archivio secondo età massima e numero minimo da conservare.",
	"archive_max_age_days":                         "Età massima delle release in archivio, in giorni (0 = nessun limite).",
	"archive_keep_min":                             "Numero minimo di release recenti da conservare sempre in archivio.",
	"cleanup_min_score_diff":                       "Differenza minima di punteggio per sostituire un file esistente con uno migliore (cleanup).",
	"upgrade_until_score":                          "Quando il file in libreria ha almeno questo punteggio non si cercano più miglioramenti; resta accettato solo un REPACK o PROPER che corregge una release difettosa. Riferimenti: 1080p WEB-DL H.264 ≈ 1280, 1080p WEB-DL H.265 DD+ ≈ 1480, 2160p ≈ 2480. 0 = migliora sempre. Per fermare del tutto gli upgrade di un solo titolo usa «Niente upgrade» nella sua scheda.",
	"upgrade_min_score_diff":                       "Differenza minima di punteggio per sostituire un file con un upgrade migliore.",
	"tvdb_api_key":                                 "Chiave API v4 di TheTVDB per ricerca serie e metadati.",
	"tvdb_language":                                "Lingua preferita per i metadati TVDB (es. ita, eng).",
	"stop_on_old_page_threshold":                   "Quante pagine di elenco leggere per ogni feed (3 è un buon compromesso).",
	"rename_verify_interval":                       "Ogni quante ore verificare che i file archiviati/rinominati siano ancora presenti.",
	"move_episodes":                                "Attivo: al termine del seed la sorgente scaricata viene eliminata (il file resta in libreria). Spento: la sorgente scaricata viene copiata in libreria e mantenuta.",
	"hardlink_seeding":                             "Attivo: un file che resta in seed entra in libreria come hardlink, cioè un secondo nome per gli stessi dati, senza occupare spazio due volte. Cancellare uno dei due nomi non tocca l'altro. Funziona solo se download e libreria sono sullo stesso filesystem; altrimenti gextto copia come prima.",
	"auth_enabled":                                 "Spento (predefinito): chiunque raggiunga gextto lo usa, come in una LAN fidata. Acceso: chi non è in rete locale deve fare il login o usare la chiave API. Resta aperto finché non imposti una password o una chiave. Se resti chiuso fuori, avvia gextto con GEXTTO_AUTH_DISABLE=1.",
	"auth_local_bypass":                            "Acceso (predefinito): dalla rete di casa (127.0.0.1, 192.168.x.x, 10.x.x.x, 172.16-31.x.x) non serve il login. Dietro un reverse proxy conta l'indirizzo reale del client inoltrato dal proxy.",
	"auth_username":                                "Nome utente per il login (predefinito admin).",
	"auth_password":                                "Password per il login. Viene salvata solo come hash; lascia vuoto per non cambiarla.",
	"auth_api_key":                                 "Chiave per script, TUI (variabile GEXTTO_API_KEY) e calendario iCal: header X-Api-Key oppure ?apikey= nell'indirizzo. Scegli una stringa lunga e casuale.",
	"debug_enabled":                                "Attiva log dettagliati e diagnostiche periodiche per il debug.",
	"jellyfin_url":                                 "URL del server Jellyfin (es. http://127.0.0.1:8096).",
	"jellyfin_api_key":                             "API key generata in Jellyfin → Dashboard → API Keys.",
	"plex_url":                                     "URL del server Plex (es. http://127.0.0.1:32400).",
	"jellyfin_path_mappings":                       "Solo se Jellyfin vede la libreria con percorsi diversi (es. Docker): una riga per cartella, percorso_gextto=percorso_jellyfin. Serve per chiedere a Jellyfin di aggiornare solo la cartella appena cambiata.",
	"plex_path_mappings":                           "Solo se Plex vede la libreria con percorsi diversi (es. Docker): una riga per cartella, percorso_gextto=percorso_plex. Serve per chiedere a Plex di aggiornare solo la cartella appena cambiata.",
	"plex_token":                                   "Token X-Plex-Token per accedere alla libreria Plex.",
	"simkl_client_id":                              "Client ID dell'app Simkl.",
	"simkl_calendar_days":                          "Quanti giorni avanti mostrare nel calendario Simkl.",
	"active":                                       "Attiva o disattiva il daemon Gextto: cicli automatici e download.",
	"websearch_engines":                            "Motori di ricerca web usati per il gap-filling quando feed e indexer non trovano nulla.",
	"content_filters":                              "Le release che contengono queste parole o script (es. [porno]) vengono escluse.",
	"libtorrent_preallocate":                       "Riserva subito tutto lo spazio su disco prima di iniziare il download.",
	"tmdb_api_key":                                 "Chiave API TMDB per titoli, poster e metadati.",
	"libtorrent_torrent_copy_dir":                  "Copia qui i file .torrent dei download (vuoto = nessuna copia).",
	"torrent_backend":                              "Motore torrent attivo (libtorrent integrato, qBittorrent-nox o gx-torrent).",
	"qbittorrent_url":                              "URL dell'interfaccia Web di qBittorrent-nox (es. http://127.0.0.1:8080).",
	"qbittorrent_username":                         "Utente dell'interfaccia Web di qBittorrent-nox.",
	"qbittorrent_password":                         "Password dell'interfaccia Web di qBittorrent-nox (non visualizzata).",
	"qbittorrent_category":                         "Categoria applicata ai torrent aggiunti a qBittorrent-nox.",
	"qbittorrent_tag":                              "Tag applicato ai torrent aggiunti a qBittorrent-nox.",
	"qbittorrent_request_timeout_secs":             "Timeout in secondi delle richieste HTTP verso qBittorrent-nox.",
	"qbittorrent_poll_interval_ms":                 "Intervallo in millisecondi tra due letture dello stato dei torrent.",
	"qbittorrent_path_mappings":                    "Mappatura dei percorsi tra Gextto e qBittorrent-nox, una per riga (locale=remoto).",
	"qbittorrent_managed":                          "Gextto scarica da sé l'ultima release di qBittorrent-nox, la installa nella cartella dell'applicazione (accanto a gexttod), la avvia e la ferma con il servizio e la aggiorna (con backup e rollback). Il motore in uso però si sceglie dalla voce «Motore torrent»: questa opzione non lo cambia.",
	"gxtorrent_url":                                "URL dell'interfaccia API di gx-torrent (es. http://127.0.0.1:8890).",
	"gxtorrent_listen":                             "Indirizzo di ascolto del demone: la pagina web e l'API sono aperte su tutta la LAN (predefinito 0.0.0.0:8890). Il traffico peer usa sempre la porta singola/le libtorrent_port_*. Se ascolti in rete serve gxtorrent_token (senza token Gextto avvia il demone in -insecure e lo segnala nel log). Per tenerlo solo su questo server usa 127.0.0.1:8890.",
	"gxtorrent_request_timeout_secs":               "Timeout in secondi delle richieste HTTP verso gx-torrent.",
	"gxtorrent_poll_interval_ms":                   "Intervallo minimo in millisecondi tra due letture dello stato dei torrent (250–60000, predefinito 1500). La coda è gestita da gx-torrent stesso, non dipende da questo valore.",
	"gxtorrent_managed":                            "Se attivo (predefinito), Gextto avvia gx-torrent da sé (l'eseguibile accanto a gexttod, installato da make/install.sh), lo riavvia se si chiude e lo ferma all'uscita. Se all'avvio trova già un gx-torrent in ascolto sull'URL, usa quello. Disattivalo se lo gestisci tu (es. servizio systemd).",
	"gxtorrent_token":                              "Segreto condiviso con gx-torrent (header X-Gx-Token). Facoltativo se gx-torrent ascolta solo su 127.0.0.1; obbligatorio se lo esponi in rete. Non visualizzato.",
	"gxtorrent_proxy":                              "Proxy per gx-torrent: socks5://utente:password@host:porta oppure http://host:porta. Peer, tracker HTTP e web seed passano dal proxy; DHT e tracker UDP vengono spenti per non uscire fuori dal proxy. Non visualizzato.",
}

// uiSettingTooltip returns the tooltip for a setting key. Score weights without
// a specific entry get a generic explanation.
func uiSettingTooltip(key string) string {
	if text, ok := uiSettingTooltipText[key]; ok {
		return text
	}
	if strings.HasPrefix(key, "score_") {
		return "Peso usato per scegliere la release migliore: più alto = più preferito."
	}
	return ""
}
