package gextto

// uiweb_settings.go contains the curated search index and tabs used by the
// server-rendered settings page.

type uiSettingDef struct{ Key, Label, Tab string }

type uiSettingsTab struct{ ID, Label string }

// uiScoreSettingDefs is the canonical score editor. Score keys are normally
// absent until edited, so deriving the UI from persisted settings would leave a
// fresh installation with no score controls at all.
var uiScoreSettingDefs = []uiSettingDef{
	{Key: "score_res_2160p", Label: "2160p", Tab: "scores"}, {Key: "score_res_1080p", Label: "1080p", Tab: "scores"},
	{Key: "score_res_720p", Label: "720p", Tab: "scores"}, {Key: "score_res_576p", Label: "576p", Tab: "scores"},
	{Key: "score_res_480p", Label: "480p", Tab: "scores"}, {Key: "score_res_360p", Label: "360p", Tab: "scores"},
	{Key: "score_source_bluray", Label: "BluRay", Tab: "scores"}, {Key: "score_source_remux", Label: "Remux", Tab: "scores"},
	{Key: "score_source_webdl", Label: "WEB-DL", Tab: "scores"}, {Key: "score_source_webrip", Label: "WEBRip", Tab: "scores"},
	{Key: "score_source_hdtv", Label: "HDTV", Tab: "scores"}, {Key: "score_source_dvdrip", Label: "DVDRip", Tab: "scores"},
	{Key: "score_codec_h265", Label: "H.265 / HEVC", Tab: "scores"}, {Key: "score_codec_h264", Label: "H.264 / AVC", Tab: "scores"},
	{Key: "score_audio_truehd", Label: "Dolby TrueHD", Tab: "scores"}, {Key: "score_audio_dts-hd", Label: "DTS-HD", Tab: "scores"},
	{Key: "score_audio_dts", Label: "DTS", Tab: "scores"}, {Key: "score_audio_ddp", Label: "Dolby Digital Plus", Tab: "scores"},
	{Key: "score_audio_ac3", Label: "AC3", Tab: "scores"}, {Key: "score_audio_5.1", Label: "5.1", Tab: "scores"},
	{Key: "score_audio_aac", Label: "AAC", Tab: "scores"}, {Key: "score_audio_mp3", Label: "MP3", Tab: "scores"},
	{Key: "score_bonus_dv", Label: "Dolby Vision", Tab: "scores"}, {Key: "score_bonus_hdr", Label: "HDR", Tab: "scores"},
	{Key: "score_bonus_proper", Label: "PROPER", Tab: "scores"}, {Key: "score_bonus_repack", Label: "REPACK", Tab: "scores"},
	{Key: "score_bonus_real", Label: "REAL", Tab: "scores"},
}

var uiScoreSettingKeys = func() map[string]bool {
	keys := make(map[string]bool, len(uiScoreSettingDefs))
	for _, def := range uiScoreSettingDefs {
		keys[def.Key] = true
	}
	return keys
}()

// Score keys that are deliberately not editable in the Punteggi tab.
//
// The aliases (x265/hevc/x264/avc/eac3) are folded into one canonical key per
// parsed token. The *_unknown/_mult keys are legacy or orphan values the scorer
// never reads: showing them would offer a control that does nothing.
var uiDeprecatedScoreSettingKeys = map[string]bool{
	"score_codec_x265": true, "score_codec_hevc": true, "score_codec_x264": true,
	"score_codec_avc": true, "score_audio_eac3": true,
	"score_res_mult": true, "score_res_unknown": true,
	"score_codec_unknown": true, "score_audio_unknown": true,
	"score_source_unknown": true,
}

var uiSettingsTabs = []uiSettingsTab{
	{ID: "daemon", Label: "Daemon"},
	{ID: "sources", Label: "Sorgenti"},
	{ID: "libtorrent", Label: "Libtorrent"},
	{ID: "backend", Label: "Motore torrent"},
	{ID: "scores", Label: "Punteggi"},
	{ID: "rename", Label: "Rinomina"},
	{ID: "advanced", Label: "Avanzate"},
	{ID: "acquisition", Label: "Acquisizione"},
	{ID: "seeding", Label: "Seed e completamento"},
	{ID: "notify", Label: "Notifiche"},
	{ID: "paths", Label: "Percorsi"},
	{ID: "i18n", Label: "Traduzioni"},
}

var uiSettingsIndex = []uiSettingDef{
	{Key: "refresh_interval", Label: "Ricerca automatica serie/film (secondi)", Tab: "daemon"},
	{Key: "max_release_age_days", Label: "Età massima release (giorni)", Tab: "daemon"},
	{Key: "gap_fill_max_per_series", Label: "Gap massimi per serie/ciclo", Tab: "daemon"},
	{Key: "gap_filling", Label: "Gap filling attivo", Tab: "daemon"},
	{Key: "gap_deep_interval_hours", Label: "Intervallo deep search (ore)", Tab: "daemon"},
	{Key: "gap_deep_max_per_cycle", Label: "Deep search massime per ciclo", Tab: "daemon"},
	{Key: "cycle_title_search", Label: "Ricerca titoli online nel ciclo", Tab: "daemon"},
	{Key: "active", Label: "Attivo", Tab: "daemon"},
	{Key: "blacklist", Label: "Blacklist (una parola per riga)", Tab: "sources"},
	{Key: "libtorrent_enabled", Label: "Client abilitato", Tab: "libtorrent"},
	{Key: "libtorrent_dynamic_queue", Label: "Auto-gestione dinamica coda e risorse", Tab: "libtorrent"},
	{Key: "libtorrent_auto_optimize", Label: "Ottimizzazione continua (periodica)", Tab: "libtorrent"},
	{Key: "libtorrent_preallocate", Label: "Prealloca lo spazio su disco", Tab: "libtorrent"},
	{Key: "libtorrent_dynamic_queue_min", Label: "Slot download dinamici minimi", Tab: "libtorrent"},
	{Key: "libtorrent_dynamic_queue_max", Label: "Slot download dinamici massimi", Tab: "libtorrent"},
	{Key: "libtorrent_dont_count_slow_torrents", Label: "Non contare i torrent fermi negli slot attivi", Tab: "libtorrent"},
	{Key: "libtorrent_stall_after_min", Label: "Considera stalled dopo (minuti)", Tab: "seeding"},
	{Key: "libtorrent_stall_retry_min", Label: "Retry stalled (minuti)", Tab: "seeding"},
	{Key: "libtorrent_stall_giveup_min", Label: "Rimozione stalled (minuti, 0 = disattivata)", Tab: "seeding"},
	{Key: "libtorrent_dead_swarm_giveup_min", Label: "Rimozione dead swarm (minuti, 0 = disattivata)", Tab: "seeding"},
	{Key: "libtorrent_sequential", Label: "Download sequenziale", Tab: "libtorrent"},
	{Key: "libtorrent_active_downloads", Label: "Download attivi", Tab: "libtorrent"},
	{Key: "libtorrent_active_seeds", Label: "Seed attivi", Tab: "libtorrent"},
	{Key: "libtorrent_active_limit", Label: "Limite torrent attivi", Tab: "libtorrent"},
	{Key: "libtorrent_seed_ratio", Label: "Seed ratio globale (0 = infinito)", Tab: "seeding"},
	{Key: "libtorrent_seed_time", Label: "Seed massimo (minuti, fallback)", Tab: "seeding"},
	{Key: "libtorrent_seed_time_days", Label: "Seed massimo (giorni)", Tab: "seeding"},
	{Key: "auto_remove_completed", Label: "Elimina i completati dopo il seed", Tab: "seeding"},
	{Key: "libtorrent_connections_limit", Label: "Limite connessioni totali", Tab: "libtorrent"},
	{Key: "libtorrent_upload_slots_limit", Label: "Slot upload", Tab: "libtorrent"},
	{Key: "libtorrent_half_open_limit", Label: "Half-open limit", Tab: "libtorrent"},
	{Key: "libtorrent_max_connections_per_torrent", Label: "Connessioni max per torrent", Tab: "libtorrent"},
	{Key: "libtorrent_max_uploads_per_torrent", Label: "Upload max per torrent", Tab: "libtorrent"},
	{Key: "libtorrent_aio_threads", Label: "Thread AIO disco", Tab: "libtorrent"},
	{Key: "libtorrent_cache_size", Label: "Cache disco (blocchi, -1 auto)", Tab: "libtorrent"},
	{Key: "libtorrent_cache_expiry", Label: "Scadenza cache (s)", Tab: "libtorrent"},
	{Key: "libtorrent_alert_queue_size", Label: "Coda alert", Tab: "libtorrent"},
	{Key: "libtorrent_dht", Label: "DHT", Tab: "libtorrent"},
	{Key: "libtorrent_pex", Label: "PEX", Tab: "libtorrent"},
	{Key: "libtorrent_lsd", Label: "LSD", Tab: "libtorrent"},
	{Key: "libtorrent_upnp", Label: "UPnP", Tab: "libtorrent"},
	{Key: "libtorrent_natpmp", Label: "NAT-PMP", Tab: "libtorrent"},
	{Key: "libtorrent_utp", Label: "uTP", Tab: "libtorrent"},
	{Key: "libtorrent_prefer_rc4", Label: "Preferisci RC4", Tab: "libtorrent"},
	{Key: "libtorrent_announce_to_all_trackers", Label: "Annuncia a tutti i tracker", Tab: "libtorrent"},
	{Key: "libtorrent_announce_to_all_tiers", Label: "Annuncia a tutti i tier", Tab: "libtorrent"},
	{Key: "libtorrent_allow_multiple_connections_per_ip", Label: "Più connessioni per IP", Tab: "libtorrent"},
	{Key: "libtorrent_announce_interval", Label: "Intervallo announce (s)", Tab: "libtorrent"},
	{Key: "libtorrent_torrent_connect_boost", Label: "Connect boost", Tab: "libtorrent"},
	{Key: "libtorrent_dht_bootstrap_nodes", Label: "Nodi bootstrap DHT", Tab: "libtorrent"},
	{Key: "libtorrent_encryption", Label: "Cifratura", Tab: "libtorrent"},
	{Key: "libtorrent_apply_ip_filter", Label: "Applica IP filter", Tab: "libtorrent"},
	{Key: "libtorrent_ipfilter_url", Label: "IP filter (file/URL)", Tab: "libtorrent"},
	{Key: "libtorrent_listen_interfaces", Label: "Interfacce listen", Tab: "libtorrent"},
	{Key: "libtorrent_outgoing_interface", Label: "Interfaccia uscente", Tab: "libtorrent"},
	{Key: "libtorrent_ramdisk_dir", Label: "Cartella RAM disk", Tab: "libtorrent"},
	{Key: "libtorrent_ramdisk_enabled", Label: "Usa il RAM disk", Tab: "libtorrent"},
	{Key: "libtorrent_ramdisk_threshold_gb", Label: "Dimensione massima per torrent (GB)", Tab: "libtorrent"},
	{Key: "libtorrent_ramdisk_margin_gb", Label: "Margine libero da mantenere (GB)", Tab: "libtorrent"},
	{Key: "libtorrent_ramdisk_min_free_bytes", Label: "Spazio minimo libero (byte, 0 = dal margine)", Tab: "libtorrent"},
	{Key: "libtorrent_port_min", Label: "Porta minima", Tab: "libtorrent"},
	{Key: "libtorrent_port_max", Label: "Porta massima", Tab: "libtorrent"},
	{Key: "libtorrent_dl_limit", Label: "Download globale (KiB/s, 0 = illimitato)", Tab: "libtorrent"},
	{Key: "libtorrent_ul_limit", Label: "Upload globale (KiB/s, 0 = illimitato)", Tab: "libtorrent"},
	{Key: "libtorrent_sched_enabled", Label: "Programmazione velocità attiva", Tab: "libtorrent"},
	{Key: "libtorrent_sched_start", Label: "Programmazione — ora inizio (HH:MM)", Tab: "libtorrent"},
	{Key: "libtorrent_sched_end", Label: "Programmazione — ora fine (HH:MM)", Tab: "libtorrent"},
	{Key: "libtorrent_sched_days", Label: "Programmazione — giorni (0=Lun … 6=Dom, es. 0,1,2,3,4)", Tab: "libtorrent"},
	{Key: "libtorrent_sched_dl_limit", Label: "Programmazione — download (KiB/s)", Tab: "libtorrent"},
	{Key: "libtorrent_sched_ul_limit", Label: "Programmazione — upload (KiB/s)", Tab: "libtorrent"},
	{Key: "libtorrent_extra_settings", Label: "Impostazioni libtorrent avanzate", Tab: "libtorrent"},
	{Key: "torrent_backend", Label: "Motore torrent", Tab: "backend"},
	{Key: "qbittorrent_url", Label: "qBittorrent-nox — URL Web API", Tab: "backend"},
	{Key: "qbittorrent_username", Label: "qBittorrent-nox — utente", Tab: "backend"},
	{Key: "qbittorrent_password", Label: "qBittorrent-nox — password", Tab: "backend"},
	{Key: "qbittorrent_category", Label: "qBittorrent-nox — categoria", Tab: "backend"},
	{Key: "qbittorrent_tag", Label: "qBittorrent-nox — tag", Tab: "backend"},
	{Key: "qbittorrent_request_timeout_secs", Label: "qBittorrent-nox — timeout richieste (secondi)", Tab: "backend"},
	{Key: "qbittorrent_poll_interval_ms", Label: "qBittorrent-nox — intervallo polling (ms)", Tab: "backend"},
	{Key: "qbittorrent_path_mappings", Label: "qBittorrent-nox — mappatura percorsi", Tab: "backend"},
	{Key: "qbittorrent_managed", Label: "qBittorrent-nox — scaricato e aggiornato da Gextto", Tab: "backend"},
	{Key: "rename_episodes", Label: "Rinomina episodi", Tab: "rename"},
	{Key: "tvdb_language", Label: "Lingua TVDB (es. ita, eng)", Tab: "rename"},
	{Key: "tmdb_language", Label: "Lingua TMDB (es. it-IT)", Tab: "rename"},
	{Key: "default_language", Label: "Lingua predefinita (es. ita)", Tab: "rename"},
	{Key: "cleanup_upgrades", Label: "Cleanup upgrade", Tab: "rename"},
	{Key: "movies_flat_files", Label: "Film come file singoli (spiana le cartelle)", Tab: "rename"},
	{Key: "cleanup_min_score_diff", Label: "Differenza minima score per cleanup", Tab: "rename"},
	{Key: "upgrade_min_score_diff", Label: "Differenza minima score per upgrade", Tab: "rename"},
	{Key: "tmdb_api_key", Label: "TMDB API key", Tab: "rename"},
	{Key: "tvdb_api_key", Label: "TVDB API key", Tab: "rename"},
	{Key: "min_free_space_gb", Label: "Spazio libero minimo per scaricare (GB)", Tab: "advanced"},
	{Key: "trash_retention_days", Label: "Trash — giorni di conservazione (0 = elimina tutto)", Tab: "advanced"},
	{Key: "archive_cleanup_enabled", Label: "Pulizia automatica archivio", Tab: "advanced"},
	{Key: "archive_max_age_days", Label: "Archivio — età massima (giorni)", Tab: "advanced"},
	{Key: "archive_keep_min", Label: "Archivio — mantieni almeno N voci", Tab: "advanced"},
	{Key: "stop_on_old_page_threshold", Label: "Pagine feed da leggere", Tab: "advanced"},
	{Key: "rename_verify_interval", Label: "Verifica rinomina (ore)", Tab: "advanced"},
	{Key: "move_episodes", Label: "Sposta gli episodi/pack in archivio (non copiare)", Tab: "seeding"},
	{Key: "debug_enabled", Label: "Debug (log dettagliati)", Tab: "advanced"},
	{Key: "delay_torrent_minutes", Label: "Delay serie (minuti, 0 = nessuno)", Tab: "acquisition"},
	{Key: "delay_movies_minutes", Label: "Delay film (minuti, 0 = nessuno)", Tab: "acquisition"},
	{Key: "delay_bypass_score", Label: "Bypassa il delay sopra questo punteggio (0 = mai)", Tab: "acquisition"},
	{Key: "housekeeping_enabled", Label: "Housekeeping periodico attivo", Tab: "acquisition"},
	{Key: "housekeeping_interval_hours", Label: "Housekeeping — intervallo (ore)", Tab: "acquisition"},
	{Key: "housekeeping_retain_cycles", Label: "Housekeeping — statistiche cicli di ricerca conservate", Tab: "acquisition"},
	{Key: "housekeeping_seen_days", Label: "Housekeeping — visti nel feed (giorni, 0 = mai)", Tab: "acquisition"},
	{Key: "housekeeping_history_days", Label: "Housekeeping — storico download (giorni, 0 = conserva)", Tab: "acquisition"},
	{Key: "housekeeping_error_age_days", Label: "Housekeeping — schede errore (giorni)", Tab: "acquisition"},
	{Key: "housekeeping_gap_log_days", Label: "Housekeeping — log ricerche gap (giorni, 0 = mai)", Tab: "acquisition"},
	{Key: "housekeeping_upgrade_backup_days", Label: "Housekeeping — backup upgrade (giorni, 0 = mai)", Tab: "acquisition"},
	{Key: "media_info_backfill_enabled", Label: "Backfill MediaInfo automatico", Tab: "acquisition"},
	{Key: "media_info_backfill_interval_minutes", Label: "Backfill MediaInfo — intervallo (minuti)", Tab: "acquisition"},
	{Key: "media_info_backfill_batch", Label: "Backfill MediaInfo — file per volta", Tab: "acquisition"},
	{Key: "temp_orphan_cleanup_enabled", Label: "Sposta nel cestino i dati orfani della cartella temporanea", Tab: "acquisition"},
	{Key: "temp_orphan_min_age_days", Label: "Dati orfani — fermi da almeno (giorni)", Tab: "acquisition"},
	{Key: "notify_telegram", Label: "Telegram attivo", Tab: "notify"},
	{Key: "telegram_bot_token", Label: "Telegram bot token", Tab: "notify"},
	{Key: "telegram_chat_id", Label: "Telegram chat ID", Tab: "notify"},
	{Key: "notify_webhook_url", Label: "Webhook URL", Tab: "notify"},
	{Key: "notify_webhook_secret", Label: "Webhook secret", Tab: "notify"},
	{Key: "notify_email", Label: "Email attiva", Tab: "notify"},
	{Key: "email_smtp", Label: "SMTP", Tab: "notify"},
	{Key: "email_from", Label: "Email mittente", Tab: "notify"},
	{Key: "email_to", Label: "Email destinatario", Tab: "notify"},
	{Key: "email_password", Label: "Password email", Tab: "notify"},
	{Key: "archive_root", Label: "Cartella archivio", Tab: "paths"},
	{Key: "trash_path", Label: "Cartella trash", Tab: "paths"},
	{Key: "cleanup_action", Label: "Azione cleanup", Tab: "paths"},
	{Key: "libtorrent_dir", Label: "Cartella download", Tab: "paths"},
	{Key: "libtorrent_temp_dir", Label: "Cartella temporanea", Tab: "paths"},
	{Key: "libtorrent_torrent_copy_dir", Label: "Copia i file .torrent in", Tab: "paths"},
}

// uiSettingSearchTerms contains common concepts that are useful when searching
// for a setting but are intentionally not repeated in its visible label.
var uiSettingSearchTerms = map[string]string{
	"libtorrent_auto_optimize":               "memoria memo memory ram cache buffer ottimizzazione optimization risorse resources",
	"libtorrent_dynamic_queue":               "memoria memo memory ram coda queue risorse resources",
	"libtorrent_dynamic_queue_min":           "memoria memo memory ram coda queue risorse resources",
	"libtorrent_dynamic_queue_max":           "memoria memo memory ram coda queue risorse resources",
	"libtorrent_dont_count_slow_torrents":    "memoria memo memory ram coda queue risorse resources",
	"libtorrent_active_downloads":            "memoria memo memory ram coda queue risorse resources",
	"libtorrent_active_seeds":                "memoria memo memory ram coda queue risorse resources",
	"libtorrent_active_limit":                "memoria memo memory ram coda queue risorse resources",
	"libtorrent_cache_size":                  "memoria memo memory ram cache buffer disco disk",
	"libtorrent_cache_expiry":                "memoria memo memory ram cache buffer disco disk",
	"libtorrent_aio_threads":                 "memoria memo memory ram buffer disco disk thread threads",
	"libtorrent_ramdisk_enabled":             "memoria memo memory ram ramdisk tmpfs",
	"libtorrent_ramdisk_threshold_gb":        "memoria memo memory ram ramdisk tmpfs spazio space",
	"libtorrent_ramdisk_margin_gb":           "memoria memo memory ram ramdisk tmpfs spazio space",
	"libtorrent_ramdisk_min_free_bytes":      "memoria memo memory ram ramdisk tmpfs spazio space",
	"libtorrent_preallocate":                 "memoria memo memory ram spazio space disco disk",
	"libtorrent_connections_limit":           "memoria memo memory ram risorse resources connessioni connections",
	"libtorrent_max_connections_per_torrent": "memoria memo memory ram risorse resources connessioni connections",
	"libtorrent_max_uploads_per_torrent":     "memoria memo memory ram risorse resources upload",
	"min_free_space_gb":                      "memoria memo memory ram spazio space disco disk",
}
